language: php

php:
    - 5.6
    - 7.1
    - 7.2
    - 7.3
    - 7.4
    - 8.0
    - 8.1

matrix:
  include:
    - php: 5.6
      env: dependencies=lowest
    - php: 7.4
      env: dependencies=lowest
    - php: 8.1
      env: dependencies=lowest

before_install:
  - composer self-update

install:
  - travis_retry composer install --no-interaction --prefer-source
  - if [ "$dependencies" = "lowest" ]; then composer update --prefer-lowest --prefer-stable -n; fi;

script:
  - ./vendor/bin/phpunit --coverage-clover=coverage.clover

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
