language: php

php:
    - 5.5
    - 5.6
    - 7.1
    - 7.2
    - 7.3

matrix:
  include:
    - php: 5.5
      env: dependencies=lowest
    - php: 5.6
      env: dependencies=lowest
    - php: 7.1
      env: dependencies=lowest

before_install:
  - composer self-update

install:
  - travis_retry composer install --no-interaction --prefer-source
  - if [ "$dependencies" = "lowest" ]; then composer update --prefer-lowest --prefer-stable -n; fi;

script:
  - ./vendor/bin/phpunit --coverage-clover=coverage.clover

after_script:
    - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
    - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
