services:
  CalendR\Calendar:
    calls:
      - ['setEventManager', ['@calendr.event_manager']]

  CalendR\Event\Manager:
    class: 'CalendR\Event\Manager'

  CalendR\Bridge\Twig\CalendRExtension:
    class: 'CalendR\Bridge\Twig\CalendRExtension'
    arguments: [ '@calendr' ]
    tags:
      - { name: twig.extension }

  calendr:
    alias: 'CalendR\Calendar'
    public: true

  calendr.factory:
    alias: 'CalendR\Calendar'
    public: true

  calendr.event_manager:
    alias: 'CalendR\Event\Manager'
    public: true
